name: Push to Other Branches

on:
  push:
    branches:
      - master
      
permissions:
  contents: write

jobs:
  push-to-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push changes to other branches
        run: |
            # Configure git
            git config --local user.name "Github ci"
            git config --local user.email "team@joinmando.com"
            
            # Checkout the branch and update it with main
            git checkout mando-ai-sandbox
            
            # Push changes to a temporary branch
            TEMP_BRANCH="auto-update/mando-ai-sandbox-from-main"
            git checkout -b $TEMP_BRANCH
            git merge main --no-ff
            git push origin $TEMP_BRANCH
            
            # Create a pull request
            gh pr create --base mando-ai-sandbox --head $TEMP_BRANCH --title "Update mando-ai-sandbox from main" --body "This PR auto-updates the mando-ai-sandbox branch with changes from the main branch."
