name: Manual Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR to run workflow for'
        required: true
      test:
        description: 'pytest command to run'
        required: true
      deploy_fresh_infra:
        description: 'Is new infra required for this test?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Display input values
        run: |
          echo "PR: ${{ github.event.inputs.pr_number }}"
          echo "Command: ${{ github.event.inputs.test }}"
          echo "Deploy: ${{ github.event.inputs.deploy_fresh_infra }}"

