name: Merge Main into Temporary Branch

on:
  push:
    branches:
      - master

jobs:
  create_temp_branch_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Create Temporary Branch
        id: temp_branch
        uses: carlsberg/temporary-branch-action@1.1.3
        with:
          base: mando-ai-sandbox
          push: true

      - name: Merge main into Temporary Branch
        run: |
          git fetch origin master
          git checkout ${{ steps.temp_branch.outputs.branch }}
          git merge origin/master

      - name: Push Temporary Branch
        run: |
          git push origin ${{ steps.temp_branch.outputs.branch }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "mando-ai-sandbox"
          pr_title: "Merge changes from master into mando-ai-sandbox"
