name: Create Merge PR

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch to create PR from'
        required: true
        type: string
      temp_branch_name:
        description: 'Name for the temporary branch'
        required: true
        type: string
      pr_title:
        description: 'Title for the Pull Request'
        required: true
        type: string

jobs:
  create-merge-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "team@joinmando.com"
          
      - name: Create and checkout temporary branch
        run: |
          git checkout ${{ inputs.base_branch }}
          git checkout -b ${{ inputs.temp_branch_name }}
          
      - name: Merge main into temporary branch
        run: |
          git fetch origin master
          git merge origin/master --no-ff
          
      - name: Push temporary branch
        run: |
          git push origin ${{ inputs.temp_branch_name }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: ${{ inputs.pr_title }}
          body: |
            Automated PR to merge master into ${{ inputs.base_branch }}
          base: ${{ inputs.base_branch }}
          branch: ${{ inputs.temp_branch_name }}
          delete-branch: true
